Repository GoogleChrome/developer.chrome.com, pull requests merged in 2021-06, with the labels that each got.

#845 [devtools-blog] Update engineering blog images
  site/en/blog/css-in-js/index.md
  site/en/blog/cvd/index.md
  site/en/blog/faster-devtools-startup/index.md
  site/en/blog/issues-tab/index.md
  site/en/blog/migrating-to-js-modules/index.md
  site/en/blog/migrating-to-typescript/index.md
  site/en/blog/migrating-to-web-components/index.md
  site/en/blog/puppetaria/index.md
  site/en/blog/puppeteer-typescript/index.md
  site/en/blog/wasm-debugging-2019/index.md
  site/en/blog/wasm-debugging-2020/index.md
  site/en/blog/webauthn-tab/index.md
Labels: cla: yes, reviewers: devtools

#846 [devtools-blog] What's New in DevTools (Chrome 92)
  site/en/blog/new-in-devtools-92/index.md
  site/en/docs/devtools/updates/index.md
Labels: cla: yes, reviewers: devtools

#851 remove overly descriptive best practice
  site/en/docs/webstore/images/index.md
Labels: cla: yes

#854 Remove site banner. Add handbook entry explaining how banners work.
  site/_data/banner.yml
  site/_data/docs/handbook/toc.yml
  site/en/docs/handbook/how-to/display-a-banner/index.md
Labels: cla: yes

#704 Fixes typo in Custom Tabs Integration
  site/en/docs/android/custom-tabs/integration-guide/index.md
Labels: cla: yes

#858 Fix incorrect CWS FAQ links
  site/en/docs/webstore/complaint-faq/index.md
Labels: cla: yes

#852 chrome.scripting blog post
  site/en/blog/crx-scripting-api/index.md
  site/en/docs/extensions/whatsnew/index.md
Labels: cla: yes

#864 Pin lhci to v7
  .github/workflows/lighthouse-ci.yml
  package-lock.json
  package.json
Labels: cla: yes

#866 Fix to address incorrect terminology
  site/en/blog/crx-scripting-api/index.md
Labels: cla: yes

#865 Remove duplicated word
  site/en/blog/crx-scripting-api/index.md
Labels: cla: yes

#867 variable name typo: frame -> frames
  site/en/blog/crx-scripting-api/index.md
Labels: cla: yes

#868 Expose an XML feed for extensions posts
  site/_collections/feeds.js
Labels: cla: yes

#870 Correct last update date for the Developer Program Policies page
  site/en/docs/webstore/program_policies/index.md
Labels: cla: yes

#859 Fix incorrect CWS FAQ links (part 2)
  site/en/docs/webstore/complaint-faq/index.md
Labels: cla: yes

#821 Fix outdated `web_accessible_resources`
  site/en/docs/extensions/mv3/intro/mv3-migration/index.md
Labels: cla: yes

#871 Browser action docs use incorrect property name in sample manifest
  site/en/docs/extensions/reference/browserAction/index.md
Labels: cla: yes, extensions

#873 [devtools-blog] Introducing Memory Inspector
  site/_data/authorsData.json
  site/en/blog/memory-inspector/index.md
Labels: cla: yes, reviewers: devtools

#876 [devtools-blog] Update image
  site/en/blog/memory-inspector/index.md
Labels: cla: yes, reviewers: devtools

#847 [README] master → main
  README.md
Labels: cla: yes

#878 [Scripting Extensions article] Fix typo and add comma
  site/en/blog/crx-scripting-api/index.md
Labels: cla: yes

#837 Minor tweaks and fixes
  site/en/docs/extensions/mv3/messaging/index.md
Labels: cla: yes

#836 update the manifest.json code example to mv3
  site/en/docs/extensions/mv3/architecture-overview/index.md
Labels: cla: yes

#828 Minor tweaks to wording
  site/en/docs/extensions/mv3/getstarted/index.md
Labels: cla: yes, extensions

#793 Include group publishing link in "Register as a chrome web store developer" page
  site/en/docs/webstore/register/index.md
Labels: cla: yes

#880 Revert "Expand documentation on webRequest extra_headers (#775)"
  site/en/docs/extensions/reference/webRequest/index.md
Labels: cla: yes

#881 [devtools] fix typo
  site/en/blog/new-in-devtools-92/index.md
Labels: cla: yes, reviewers: devtools

#869 Update /docs/devtools/customize/placement/index.md with current placement options and add keyboard shortcuts for Linux/Windows/Mac
  site/en/docs/devtools/customize/placement/index.md
Labels: cla: yes

#663 Rework "what's new" page
  site/en/docs/extensions/whatsnew/index.md
Labels: cla: yes

#856 Corrected the pane name to access
  site/en/docs/devtools/storage/applicationcache/index.md
Labels: cla: yes

#855 Corrected the pane name to access
  site/en/docs/devtools/storage/websql/index.md
Labels: cla: yes

#863 [Extensions][Tabs] Give an example for mutating tabs api calls.
  site/en/docs/extensions/reference/tabs/index.md
Labels: cla: yes

#783 Add detail for how to see if a method supports promises
  site/en/docs/extensions/mv3/promises/index.md
Labels: cla: yes

#862 [Post] TablesNG
  site/_data/authorsData.json
  site/en/blog/tablesng/index.md
Labels: cla: yes

#791 Removes spurious references to apps from CRX docs
  site/en/docs/extensions/mv3/declare_permissions/index.md
  site/en/docs/extensions/mv3/devtools/index.md
  site/en/docs/extensions/mv3/faq/index.md
  site/en/docs/extensions/mv3/manifest/incognito/index.md
  site/en/docs/extensions/mv3/manifest/offline_enabled/index.md
  site/en/docs/extensions/mv3/manifest/requirements/index.md
  site/en/docs/extensions/mv3/manifest/sandbox/index.md
  site/en/docs/extensions/mv3/messaging/index.md
  site/en/docs/extensions/mv3/richNotifications/index.md
  site/en/docs/extensions/mv3/sandboxingEval/index.md
  site/en/docs/extensions/mv3/tut_analytics/index.md
  site/en/docs/extensions/mv3/xhr/index.md
Labels: cla: yes

#896 Don't assign reviewers for drafts
  .pullapprove.yml
Labels: cla: yes

#893 Fix a broken link reference
  site/en/docs/extensions/mv3/promises/index.md
Labels: cla: yes

#889 [WAR] Add documentation for use_dynamic_url.
  site/en/docs/extensions/mv3/intro/mv3-migration/index.md
  site/en/docs/extensions/mv3/manifest/web_accessible_resources/index.md
Labels: cla: yes

#899 remove banner
  site/_data/banner.yml
Labels: cla: yes

#794 Update CWS best practices page
  site/en/docs/webstore/best_practices/index.md
Labels: cla: yes

#749 Updates to webstore docs, removing spurious references
  redirects.yaml
  site/en/docs/webstore/about_webstore/index.md
  site/en/docs/webstore/apps_vs_extensions/index.md
  site/en/docs/webstore/authentication/index.md
  site/en/docs/webstore/best_practices/index.md
  site/en/docs/webstore/branding/index.md
  site/en/docs/webstore/choosing/index.md
  site/en/docs/webstore/distribution/index.md
  site/en/docs/webstore/faq/index.md
  site/en/docs/webstore/get_started/index.md
  site/en/docs/webstore/get_started_simple/index.md
  site/en/docs/webstore/hosted_apps/index.md
  site/en/docs/webstore/identify_user/index.md
  site/en/docs/webstore/images/index.md
  site/en/docs/webstore/inline_installation/index.md
  site/en/docs/webstore/inline_installation/inline_install_dialog.png
  site/en/docs/webstore/launching/index.md
  site/en/docs/webstore/migrating/index.md
  site/en/docs/webstore/one_time_payments/index.md
  site/en/docs/webstore/payments-iap/index.md
  site/en/docs/webstore/rating/index.md
  site/en/docs/webstore/samples/index.md
  site/en/docs/webstore/troubleshooting/index.md
Labels: cla: yes

#894 Add figcaption to handbook
  site/_scss/_typography.scss
  site/en/docs/handbook/components/index.md
Labels: cla: yes

#904 Tweak tabs documentation
  site/en/docs/handbook/components/index.md
Labels: cla: yes

#684 Runtime API intro
  site/en/docs/extensions/reference/runtime/index.md
Labels: cla: yes

#912 Added migration guide for the conversion measurement API
  site/en/docs/privacy-sandbox/attribution-reporting-migration/index.md
  site/en/docs/privacy-sandbox/attribution-reporting/index.md
Labels: cla: yes

#887 Adds RenderingNG post
  site/_data/authorsData.json
  site/en/blog/renderingng/index.md
Labels: cla: yes

#913 fix date on RenderingNG post
  site/en/blog/renderingng/index.md
Labels: cla: yes

#910 chrome.action blog post
  site/en/blog/mv3-actions/index.md
  site/en/docs/extensions/whatsnew/index.md
Labels: cla: yes

#911 Update private network access article
  site/en/blog/private-network-access-update/index.md
Labels: cla: yes

#908 Cleanup best practices page
  site/en/docs/webstore/best_practices/index.md
Labels: cla: yes, extensions

#801 Convert autoplay article from WebFu.
  package-lock.json
  site/_data/authorsData.json
  site/_data/i18n/tags.yml
  site/_data/supportedTags.json
  site/en/blog/autoplay/index.md
Labels: DO NOT MERGE, cla: yes

#935 Add pwa banner
  site/_data/banner.yml
Labels: cla: yes

#930 Fix typo
  site/en/docs/webstore/troubleshooting/index.md
Labels: cla: yes

#936 issue #905 - fixed typo in site/en/docs/apps/chrome_apps_on_mobile/in…
  site/en/docs/apps/chrome_apps_on_mobile/index.md
Labels: cla: no

#941 Add illustrations attribution and fix one link.
  site/en/blog/renderingng/index.md
Labels: cla: yes

#879 MV3 architecture bugfix
  site/en/docs/extensions/mv3/architecture-overview/index.md
Labels: cla: yes

#920 Add examples to Action API reference page
  site/en/docs/extensions/reference/action/index.md
Labels: cla: yes, extensions

#938 Add screenshot class to action post images
  site/en/blog/mv3-actions/index.md
Labels: cla: yes, extensions

#939 CWS publishing guide doc link update & cleanup
  site/en/docs/webstore/publish/index.md
Labels: cla: yes, extensions

#916 Update policy and FAQ docs for Apollo launch
  site/en/docs/webstore/deceptive_installation_tactics/index.md
  site/en/docs/webstore/program_policies/index.md
  site/en/docs/webstore/spam-faq/index.md
  site/en/docs/webstore/terms/index.md
Labels: cla: yes

#928 Blog post to announce new policy clarification and 2SV enforcement
  site/_data/authorsData.json
  site/en/blog/policy-update-2sv/index.md
Labels: cla: yes

#940 Set card images to auto height to avoid cropping.
  site/_scss/blocks/_blog-card.scss
  site/_scss/blocks/_featured-card.scss
Labels: cla: yes

#942 Change to H2 for sections
  site/en/blog/renderingng/index.md
Labels: cla: yes

#883 Fixed a typo
  site/en/docs/android/custom-tabs/overview/index.md
Labels: cla: yes

#944 Policy polish
  site/en/blog/policy-update-2sv/index.md
  site/en/docs/extensions/whatsnew/index.md
  site/en/docs/webstore/program_policies/index.md
Labels: cla: yes

#945 [devtools] Replace screenshot
  site/en/blog/new-in-devtools-92/index.md
Labels: cla: yes, reviewers: devtools
