Repository GoogleChrome/developer.chrome.com, pull requests merged in 2021-10, with the labels that each got.

#1535 [Privacy sandbox article] Fix Twitter handle character case
  site/en/blog/progress-in-the-privacy-sandbox-2021-09/index.md
Labels: cla: yes

#1539 Fix typo in commands API usage on '/extensions/reference/commands/'
  site/en/docs/extensions/reference/commands/index.md
Labels: cla: yes

#1493 Chromium Chronicle 25
  site/en/blog/chromium-chronicle-25/index.md
Labels: cla: yes

#1542 Add link for Scripting API reference on '/mv3/intro/mv3-overview/'
  site/en/docs/extensions/mv3/intro/mv3-overview/index.md
Labels: cla: yes

#1536 Provide User Support section
  site/en/docs/webstore/cws-dashboard-listing/index.md
  site/en/docs/webstore/manage/index.md
Labels: extensions, cla: yes

#1476 [devtools-translate] Korean-What's new in DevTools (Chrome 95)
  site/_includes/partials/devtools/ko/whats-new.md
  site/ko/blog/new-in-devtools-95/index.md
Labels: cla: yes, devtools-translate

#1540 Adds table of contents to blog posts
  site/_includes/layouts/blog-post.njk
Labels: cla: yes

#1453 Update manifest_version for an MV3 page and improve formatting
  site/en/docs/extensions/mv3/manifest/activeTab/index.md
Labels: cla: yes

#1549 Update Google Analytics tutorials sample's CRS to manifest V3
  site/en/docs/extensions/mv3/tut_analytics/index.md
Labels: cla: yes

#1522 fix extensions => extension_ids
  site/en/docs/extensions/mv3/intro/mv3-migration/index.md
  site/en/docs/extensions/mv3/manifest/web_accessible_resources/index.md
Labels: cla: yes

#1468 Updating link to personal blog
  site/en/blog/new-in-chrome-54/index.md
  site/en/blog/new-in-chrome-55/index.md
  site/en/blog/new-in-chrome-56/index.md
  site/en/blog/new-in-chrome-57/index.md
  site/en/blog/new-in-chrome-58/index.md
  site/en/blog/new-in-chrome-59/index.md
  site/en/blog/new-in-chrome-60/index.md
  site/en/blog/new-in-chrome-61/index.md
  site/en/blog/new-in-chrome-62/index.md
  site/en/blog/new-in-chrome-63/index.md
  site/en/blog/new-in-chrome-64/index.md
  site/en/blog/new-in-chrome-65/index.md
  site/en/blog/new-in-chrome-66/index.md
  site/en/blog/new-in-chrome-67/index.md
  site/en/blog/new-in-chrome-68/index.md
  site/en/blog/new-in-chrome-69/index.md
  site/en/blog/new-in-chrome-70/index.md
  site/en/blog/new-in-chrome-71/index.md
  site/en/blog/new-in-chrome-72/index.md
  site/en/blog/new-in-chrome-73/index.md
  site/en/blog/new-in-chrome-74/index.md
  site/en/blog/new-in-chrome-75/index.md
  site/en/blog/new-in-chrome-76/index.md
  site/en/blog/new-in-chrome-77/index.md
  site/en/blog/new-in-chrome-78/index.md
  site/en/blog/new-in-chrome-80/index.md
  site/en/blog/new-in-chrome-81/index.md
  site/en/blog/new-in-chrome-83/index.md
  site/en/blog/new-in-chrome-84/index.md
  site/en/blog/new-in-chrome-85/index.md
  site/en/blog/new-in-chrome-86/index.md
  site/en/blog/new-in-chrome-87/index.md
  site/en/blog/new-in-chrome-88/index.md
  site/en/blog/new-in-chrome-89/index.md
  site/en/blog/new-in-chrome-90/index.md
  site/en/blog/new-in-chrome-91/index.md
Labels: cla: yes

#1556 always use reference layout
  site/en/docs/extensions/reference/reference.11tydata.js
Labels: cla: yes

#1557 Fix typo in MV2 getting started
  site/en/docs/extensions/mv2/getstarted/index.md
Labels: cla: yes

#1544 clarify some U2F deprecation details
  site/en/blog/deps-rems-95/index.md
Labels: cla: yes

#1572 Update the UA Reduction Origin Trial Blog Post
  site/en/blog/user-agent-reduction-origin-trial/index.md
Labels: cla: yes

#1579 use HTTP JSON API for sync
  external/sync-external.js
  package-lock.json
  package.json
Labels: cla: yes

#1583 Fix some typos
  site/en/docs/apps/analytics/index.md
  site/en/docs/extensions/mv2/background_pages/index.md
  site/en/docs/extensions/mv2/external_extensions/index.md
  site/en/docs/extensions/mv2/faq/index.md
  site/en/docs/extensions/mv2/getstarted/index.md
  site/en/docs/extensions/mv2/permission_warnings/index.md
  site/en/docs/extensions/mv2/security/index.md
  site/en/docs/extensions/mv2/user_privacy/index.md
  site/en/docs/extensions/mv3/a11y/index.md
  site/en/docs/extensions/mv3/content_scripts/index.md
  site/en/docs/extensions/mv3/faq/index.md
  site/en/docs/extensions/mv3/security/index.md
  site/en/docs/extensions/mv3/service_workers/index.md
  site/en/docs/extensions/mv3/user_privacy/index.md
  site/en/docs/handbook/how-to/add-an-iframe/index.md
  site/en/docs/native-client/migration/index.html
  site/en/docs/webstore/branding/index.md
  site/en/docs/webstore/play_edu_tos/index.md
  site/en/docs/webstore/webstore_api/items/publish/index.md
Labels: cla: yes

#1573 [devtools-translate]: Chinese - What's new in DevTools (Chrome 95)
  site/zh/blog/new-in-devtools-95/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1582 Remove a paragraph from the UA Reduction blog post
  site/en/blog/user-agent-reduction-origin-trial/index.md
Labels: cla: yes

#1576 Postpone SAB deprecation trial to Chrome 103
  site/en/blog/coep-credentialless-origin-trial/index.md
  site/en/blog/enabling-shared-array-buffer/index.md
Labels: cla: yes

#1502 Workbox intro articles
  site/_data/docs/projects.yml
  site/_data/docs/workbox/toc.yml
  site/_data/i18n/docs/workbox.yml
  site/en/docs/workbox/caching-strategies-overview/index.md
  site/en/docs/workbox/index.md
  site/en/docs/workbox/service-worker-lifecycle/index.md
  site/en/docs/workbox/service-worker-overview/index.md
  site/en/docs/workbox/what-is-workbox/index.md
Labels: cla: yes

#1595 [devtools-blog] Remove draft
  site/zh/blog/new-in-devtools-95/index.md
Labels: reviewers: devtools, cla: yes

#1599 [devtools-blog] Add missing links
  site/_includes/partials/devtools/en/whats-new.md
  site/_includes/partials/devtools/es/whats-new.md
  site/_includes/partials/devtools/ko/whats-new.md
  site/_includes/partials/devtools/ru/whats-new.md
  site/_includes/partials/devtools/zh/whats-new.md
  site/zh/blog/new-in-devtools-95/index.md
Labels: reviewers: devtools, cla: yes

#1594 Update footer to remove links to devweb firehose
  site/_data/i18n/footer.yml
  site/_includes/partials/footer.njk
Labels: cla: yes

#1648 Blog post "Progress in the Privacy Sandbox (October 2021)"
  site/en/blog/progress-in-the-privacy-sandbox-2021-10/index.md
Labels: cla: yes

#1642 Upgrade to fetching chrome-types@latest, misc, fixes
  external/build/lib/dts-parse-helper.js
  external/build/lib/dts-parse.js
  external/build/types.js
  tests/external/types.js
Labels: cla: yes
