Repository GoogleChrome/developer.chrome.com, pull requests merged in 2021-05, with the labels that each got.

#731 [devtools] Update incorrect link
  site/en/blog/new-in-devtools-91/index.md
  site/en/docs/devtools/memory-inspector/index.md
Labels: reviewers: devtools

#732 [devtools] Update web vitals latest screenshot
  site/en/blog/new-in-devtools-91/index.md
Labels: reviewers: devtools

#739 [devtools-blog] Faser stack traces
  site/_data/authorsData.json
  site/en/blog/faster-stack-traces/index.md
Labels: reviewers: devtools

#741 [devtools] Update link
  site/en/docs/devtools/overview/index.md
Labels: reviewers: devtools

#745 [devtools-blog] Update to use screenshot with all 3 types of issues
  site/en/blog/new-in-devtools-91/index.md
Labels: reviewers: devtools

#755 [devtools-blog] Update Memory inspector
  site/en/docs/devtools/memory-inspector/index.md
Labels: reviewers: devtools

#697 Update mv3/content_scripts to reflect current MV3 impl
  site/en/docs/extensions/mv3/content_scripts/index.md
Labels: extensions

#795 Privacy sandbox section
  site/_data/authorsData.json
  site/_data/docs/privacy-sandbox/toc.yml
  site/_data/docs/projects.yml
  site/_data/i18n/docs/privacy-sandbox.yml
  site/_static/images/project/privacy-sandbox.svg
  site/en/docs/privacy-sandbox/attribution-reporting/index.md
  site/en/docs/privacy-sandbox/first-party-sets/index.md
  site/en/docs/privacy-sandbox/fledge/index.md
  site/en/docs/privacy-sandbox/floc/index.md
  site/en/docs/privacy-sandbox/glossary/index.md
  site/en/docs/privacy-sandbox/index.md
  site/en/docs/privacy-sandbox/overview/index.md
  site/en/docs/privacy-sandbox/status/index.md
  site/en/docs/privacy-sandbox/trust-tokens/index.md
Labels: cla: yes

#796 Updated FLoC step-by-step image
  site/en/docs/privacy-sandbox/floc/index.md
Labels: cla: yes

#797 Updated FPS OT versions
  site/en/docs/privacy-sandbox/first-party-sets/index.md
Labels: cla: yes

#798 Updated links in attribution reporting
  site/en/docs/privacy-sandbox/attribution-reporting/index.md
Labels: cla: yes

#800 Remove redundant empty tags
  site/en/docs/extensions/mv3/content_scripts/index.md
Labels: cla: yes

#802 move privacy sandbox to architecture section
  site/_data/docs/projects.yml
Labels: cla: yes

#804 guard against missing tags
  site/_includes/macros/tag.njk
Labels: cla: yes

#799 Fixing link in "Offline-First TWA" article
  site/en/docs/android/trusted-web-activity/offline-first/index.md
Labels: cla: yes

#771 Update best practices on supplying images
  site/en/docs/webstore/images/index.md
Labels: cla: yes

#805 Make banner dismissible
  site/_data/banner.yml
  site/_data/site.json
  site/_includes/partials/banner.njk
  site/_includes/partials/cookie-banner.njk
  site/_includes/partials/script.js
  site/_js/third-party/announcement-banner/announcement-banner.js
  site/_scss/blocks/_announcement-banner.scss
  site/_scss/blocks/_banner.scss
  site/_scss/blocks/_cookie-banner.scss
Labels: cla: yes

#811 Fixed link on Attribution Reporting article
  site/en/docs/privacy-sandbox/attribution-reporting/index.md
Labels: cla: yes

#816 Fix typos in `Feedback` section of `richer-pwa-installation`
  site/en/blog/richer-pwa-installation/index.md
Labels: cla: yes

#814 Fix broken link in docs
  site/en/docs/android/custom-tabs/overview/index.md
Labels: cla: yes

#824 Add insights banner back.
  site/_data/banner.yml
Labels: cla: yes

#826 [devtools-blog] Add WNDT 91 videos
  site/en/blog/new-in-devtools-91/index.md
Labels: cla: yes, reviewers: devtools

#817 Extend experimental warning in `richer-pwa-installation`.
  site/en/blog/richer-pwa-installation/index.md
Labels: cla: yes

#827 New in Chrome 91 post
  site/en/blog/new-in-chrome-91/index.md
Labels: cla: yes

#829 Add definition list to handbook.
  site/en/docs/handbook/components/index.md
Labels: cla: yes

#823 Chromium Chronicle 21
  site/en/blog/chromium-chronicle-21/index.md
Labels: cla: yes
