Repository GoogleChrome/developer.chrome.com, pull requests merged in 2021-09, with the labels that each got.

#1328 Remove parens from timeOrigin
  site/en/blog/cross-origin-isolated-hr-timers/index.md
Labels: cla: yes

#1324 CUJ Tweaks for I can distribute my item to a specific audience
  site/en/docs/webstore/cws-dashboard-distribution/index.md
Labels: P2, extensions, cla: yes

#1325 CUJ Tweaks for I want to be alerted when my item is published, rejected, or taken down
  site/en/docs/webstore/publish/index.md
Labels: extensions, cla: yes

#1331 Added information about deprecation trials
  site/en/blog/origin-trials/index.md
Labels: cla: yes

#1312 [devtools-translate] Portuguese - What's New in DevTools (Chrome 93)
  site/_includes/partials/devtools/pt/banner.md
  site/_includes/partials/devtools/pt/reach-out.md
  site/_includes/partials/devtools/pt/whats-new.md
  site/pt/blog/new-in-devtools-93/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1326 CUJ Tweaks for I can collaborate with other people to publish my extension
  site/en/docs/webstore/group-publishers/index.md
Labels: extensions, cla: yes

#1247 Update declarativeNetRequest docs for recent static ruleset changes
  site/en/docs/extensions/reference/declarativeNetRequest/index.md
Labels: cla: yes

#1338 Nit: Update index.md (remove double "to")
  site/en/blog/first-party-sets-sameparty/index.md
Labels: cla: yes

#1329 Fix open options example code
  site/en/docs/extensions/mv3/options/index.md
Labels: cla: yes

#1345 bump chrome-types-helpers
  package-lock.json
  package.json
Labels: cla: yes

#1349 Update index.md
  site/en/docs/extensions/mv2/manifest/sandbox/index.md
Labels: cla: no

#1314 [devtools-translate] Japanese - What's New in DevTools (Chrome 93)
  site/_includes/partials/devtools/ja/banner.md
  site/_includes/partials/devtools/ja/reach-out.md
  site/_includes/partials/devtools/ja/whats-new.md
  site/ja/blog/new-in-devtools-93/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1342 Added warning about end of origin trial and information about flags
  site/en/blog/floc/index.md
Labels: cla: yes

#1350 customize: Display Figure 3 at visible size
  site/en/docs/devtools/customize/index.md
Labels: cla: yes

#1354 Added troubleshooting suggestion: the origin trial is not disabled by Chrome settings
  site/en/blog/origin-trial-troubleshooting/index.md
Labels: cla: yes

#1360 bump gts to >3, remove unused deps
  .eslintrc.js
  package-lock.json
  package.json
  server/redirect.js
  site/_collections/tags.js
  site/_includes/scripts/masonry.js
  site/_js/actions/side-nav.js
  site/_js/web-components/navigation-rail.js
  site/_js/web-components/navigation-tree.js
  site/_js/web-components/search-box.js
  site/_js/web-components/side-nav.js
  site/_js/web-components/toc-active.js
  site/_js/web-components/top-nav.js
  site/_js/web-components/web-tabs.js
Labels: cla: yes

#1339 [devtools-translate] Spanish - What's New in DevTools (Chrome 93)
  site/_includes/partials/devtools/es/reach-out.md
  site/_includes/partials/devtools/es/whats-new.md
  site/es/blog/new-in-devtools-93/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1359 Add note about DAL request status code requirements
  site/en/blog/site-affiliation/index.md
Labels: cla: yes

#1362 Update image link
  site/ja/blog/new-in-devtools-93/index.md
Labels: reviewers: devtools, cla: yes

#1363 Link to "deprecation trials"
  site/en/blog/private-network-access-update/index.md
Labels: cla: yes

#1355 [devtools-translate] Spanish - What's New in DevTools (Chrome 94)
  site/_includes/partials/devtools/es/whats-new.md
  site/es/blog/new-in-devtools-92/index.md
  site/es/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1357 add Workbox documentation section
  site/_data/docs/tocIndex.js
  site/_data/docs/workbox/styles.yml
  site/_data/docs/workbox/toc.yml
  site/_data/lib/links.js
  site/_includes/layouts/project-landing.njk
  site/_scss/_theme.scss
  site/en/docs/handbook/how-to/add-a-project/index.md
  site/en/docs/index.md
  site/en/docs/workbox/index.md
  site/en/docs/workbox/workbox.11tydata.js
Labels: cla: yes

#1343 [devtools-translate] Portuguese - What's New in DevTools (Chrome 94)
  site/_includes/partials/devtools/pt/whats-new.md
  site/pt/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1340 Translate my desc
  site/_data/authorsData.json
Labels: DO NOT MERGE, cla: yes

#1370 spend more money
  .cloudbuild/deploy.yaml
Labels: cla: yes

#1374 Added embedded videos to FLEDGE and Attribution Reporting articles
  site/en/docs/privacy-sandbox/attribution-reporting/index.md
  site/en/docs/privacy-sandbox/fledge/index.md
Labels: cla: yes

#1375 Add newline to Asides so markdown works
  site/_shortcodes/Aside.js
Labels: cla: yes

#1371 Update webdev infra version
  package-lock.json
  package.json
Labels: cla: yes

#1372 Add supported language links for blog post
  .eleventy.js
  site/_filters/urls.js
  site/_includes/partials/post-headline.njk
  site/_includes/partials/updated.njk
  site/_scss/blocks/_dates.scss
  site/_scss/main.scss
  site/_shortcodes/LanguageList.js
  tests/site/_filters/urls.js
Labels: cla: yes

#1386 fix URL switcher links were being mangled
  site/_data/i18n/common.yml
  site/_filters/urls.js
  site/_includes/partials/post-headline.njk
  site/_shortcodes/LanguageList.js
  site/_transforms/pretty-urls.js
Labels: cla: yes

#1388 docs: fix typo
  .eleventy.js
Labels: cla: yes

#1384 Add missing URL for 'session cookies' link
  site/en/docs/devtools/storage/cookies/index.md
Labels: cla: yes

#1381 Update extension API reference docs "Cookies" according to mv3 changes.
  site/en/docs/extensions/reference/cookies/index.md
Labels: cla: yes

#1373 Remove lint rules
  .remarkrc.js
  tools/linting/no-dash-spaces.js
  tools/linting/no-smart-quotes.js
Labels: cla: yes

#1366 CUJ Tweaks for I know where to find help
  site/en/docs/webstore/about_webstore/index.md
  site/en/docs/webstore/faq/index.md
Labels: P2, extensions, cla: yes

#1394 Update CSP link
  site/en/blog/cvd/index.md
  site/en/blog/new-in-devtools-89/index.md
Labels: cla: yes

#1395 minor devtools tutorial fix
  site/en/docs/devtools/workspaces/index.md
Labels: cla: yes

#1379 Remove links to individual files in MV2 getting started docs
  site/en/docs/extensions/mv2/getstarted/index.md
Labels: bug, extensions, cla: yes

#1367 [lighthouse] What's new in Lighthouse 8.4
  site/_data/authorsData.json
  site/_data/i18n/tags.yml
  site/en/blog/lighthouse-8-4/index.md
Labels: cla: yes

#1401 fix typo in What's new in Lighthouse 8.4
  site/en/blog/lighthouse-8-4/index.md
Labels: cla: yes

#1406 Fix heading level and typo in What's New in Lighthouse 8.4
  site/en/blog/lighthouse-8-4/index.md
Labels: cla: yes

#1403 Add note about cloning underneath 'Clone the repo' heading
  README.md
Labels: cla: yes

#1399 Chrome label fixes
  site/_data/chrome.js
  site/_data/i18n/common.yml
  site/_includes/layouts/tags-landing.njk
  site/_includes/macros/cards/releases-card.njk
  site/_includes/macros/tag.njk
  site/_scss/blocks/_release-card.scss
  site/_utils/tags-11tydata.js
  site/en/releases/index.md
  tests/site/_data/chrome.js
Labels: cla: yes

#1408 re-add chrome-95 to lighthouse post
  site/en/blog/lighthouse-8-4/index.md
Labels: cla: yes

#1410 move to web-dev-uploads
  site/_data/site.json
  site/_data/tweets.js
  site/en/docs/extensions/mv2/getstarted/index.md
  site/en/docs/extensions/mv2/overview/index.md
  site/en/docs/extensions/mv2/tut_debugging/index.md
  site/en/docs/extensions/mv3/getstarted/index.md
  site/en/docs/extensions/mv3/overview/index.md
  site/en/docs/handbook/how-to/add-media/index.md
  site/en/docs/webstore/branding/index.md
  tests/site/_shortcodes/img.js
  tests/site/_shortcodes/video.js
Labels: cla: yes

#1400 Added kritisapra@ to blog authors
  site/_data/authorsData.json
Labels: reviewers: devtools, cla: yes

#1411 [devtools-blog] Fix hero images, links
  site/_includes/partials/devtools/es/whats-new.md
  site/_includes/partials/devtools/ja/whats-new.md
  site/_includes/partials/devtools/pt/whats-new.md
  site/_includes/partials/devtools/zh/whats-new.md
  site/en/blog/new-in-devtools-94/index.md
  site/es/blog/new-in-devtools-92/index.md
  site/zh/blog/new-in-devtools-92/index.md
Labels: reviewers: devtools, cla: yes

#1409 fix changelog link and h2 title in lighthouse post
  site/en/blog/lighthouse-8-4/index.md
Labels: cla: yes

#1402 Add author info for abeyad@
  site/_data/authorsData.json
Labels: cla: yes

#1404 Add author info for arichiv@
  site/_data/authorsData.json
Labels: cla: yes

#1415 [devtools] Fix typo
  site/en/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes

#1417 Update UA reduction OT post
  site/en/blog/user-agent-reduction-origin-trial/index.md
Labels: cla: yes

#1353 VideoNG article
  site/_data/authorsData.json
  site/en/blog/videong/index.md
Labels: cla: yes

#1419 Improve formatting
  site/en/blog/modernising-css-infra-in-devtools/index.md
Labels: reviewers: devtools, cla: yes

#1420 Fix typo in example
  site/en/blog/cross-device-webotp/index.md
Labels: cla: yes

#1382 Add SameParty attribute to list of cookie fields
  site/en/docs/devtools/storage/cookies/index.md
Labels: cla: yes

#1418 [devtools] Add new tag for a series
  site/_data/i18n/tags.yml
  site/_data/supportedTags.json
  site/en/blog/migrating-to-js-modules/index.md
  site/en/blog/migrating-to-typescript/index.md
  site/en/blog/migrating-to-web-components/index.md
  site/en/blog/modernising-css-infra-in-devtools/index.md
Labels: reviewers: devtools, cla: yes

#1390 [devtools-translate] Korean - What's new in DevTools (Chrome 93)
  site/_includes/partials/devtools/ko/banner.md
  site/_includes/partials/devtools/ko/reach-out.md
  site/_includes/partials/devtools/ko/whats-new.md
  site/ko/blog/new-in-devtools-93/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1396 [devtools-translate] Japanese - What's New in DevTools (Chrome 94)
  site/_includes/partials/devtools/ja/whats-new.md
  site/ja/blog/new-in-devtools-93/index.md
  site/ja/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1422 Fix name
  site/ko/blog/new-in-devtools-93/index.md
Labels: reviewers: devtools, cla: yes

#1377 Uniquely identifying PWAs with the web app manifest id property
  site/en/blog/pwa-manifest-id/index.md
Labels: cla: yes

#1430 fix: minor typo in modern css devtools
  site/en/blog/modernising-css-infra-in-devtools/index.md
Labels: cla: yes

#1431 Fix typo where the variable name was a keyword
  site/en/docs/extensions/reference/runtime/index.md
Labels: cla: yes

#1427 User ratings and Store item Stats
  site/en/docs/webstore/manage/index.md
Labels: extensions, cla: yes

#1435 Fix typo in Tooltip (title) section of chrome.action reference page
  site/en/docs/extensions/reference/action/index.md
Labels: cla: yes

#1446 Fix broken links in /devtools/overview/#elements
  site/en/docs/devtools/overview/index.md
Labels: cla: yes

#1337 deps-rems-91: add followup note on deprecating third-party iframe `alert()` & Co.
  site/en/blog/deps-rems-91/index.md
Labels: cla: yes

#1445 Add related links to manifest id doc
  site/en/blog/pwa-manifest-id/index.md
Labels: cla: yes

#1448 Remove browserAction (MV2 availability) from customize extension table on MV3 page
  site/en/docs/extensions/mv3/devguide/index.md
Labels: cla: yes

#1432 Add chrome.action API to the customize extension user interface table
  site/en/docs/extensions/mv3/devguide/index.md
Labels: extensions, cla: yes

#1412 [devtools-translate] Korean - What's new in DevTools (Chrome 94)
  site/_includes/partials/devtools/ko/whats-new.md
  site/ko/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1323 [devtools-translate] Russian - What's New in DevTools (Chrome 94)
  site/_includes/partials/devtools/ru/reach-out.md
  site/_includes/partials/devtools/ru/whats-new.md
  site/ru/blog/new-in-devtools-93/index.md
  site/ru/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1455 [devtools-blog] Update WNDT94 video link and korean hero image
  site/en/blog/new-in-devtools-94/index.md
  site/es/blog/new-in-devtools-94/index.md
  site/ja/blog/new-in-devtools-94/index.md
  site/ko/blog/new-in-devtools-94/index.md
  site/pt/blog/new-in-devtools-94/index.md
  site/ru/blog/new-in-devtools-94/index.md
Labels: cla: yes

#1433 [devtools-translate] Chinese - What's new in DevTools (Chrome 94)
  site/zh/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1459 [devtools-blog] What's new in DevTools 59 migration
  site/en/blog/new-in-devtools-59/index.md
Labels: reviewers: devtools, cla: yes

#1460 [devtools-blog] What's new in DevTools (Chrome 95)
  site/_includes/partials/devtools/en/whats-new.md
  site/en/blog/new-in-devtools-95/index.md
  site/es/blog/new-in-devtools-95/index.md
  site/ja/blog/new-in-devtools-95/index.md
  site/ko/blog/new-in-devtools-95/index.md
  site/pt/blog/new-in-devtools-95/index.md
  site/ru/blog/new-in-devtools-95/index.md
  site/zh/blog/new-in-devtools-95/index.md
Labels: reviewers: devtools, cla: yes

#1443 Added information about using command-line flags to enable FLEDGE in …
  site/en/docs/privacy-sandbox/fledge/index.md
Labels: cla: yes

#1470 [devtools-translate] Remove a bunch of unwanted Chinese words
  site/zh/blog/new-in-devtools-94/index.md
Labels: cla: yes

#1423 wrap choices in parens when used in array
  site/_includes/macros/render-type.njk
Labels: cla: yes

#1474 [devtools-blog] Update images
  site/es/blog/new-in-devtools-94/index.md
  site/ja/blog/new-in-devtools-94/index.md
  site/ko/blog/new-in-devtools-94/index.md
  site/pt/blog/new-in-devtools-94/index.md
  site/ru/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes

#1454 Fix broken links on '/mv3/tut_oauth/' page
  site/en/docs/extensions/mv3/tut_oauth/index.md
Labels: cla: yes

#1480 allow more varied release data from Chrome
  site/_data/chrome.js
  site/_includes/layouts/releases-landing.njk
  site/_includes/macros/cards/releases-card.njk
  site/_utils/tags-11tydata.js
Labels: cla: yes

#1452 Change manifest_version to 3 in code snippet on '/mv3/tut_debugging/#declare_permission'
  site/en/docs/extensions/mv3/tut_debugging/index.md
Labels: cla: yes

#1486 Update wrong date
  site/en/docs/devtools/css/grid/index.md
Labels: reviewers: devtools, cla: yes

#1467 NIC94 Post
  site/en/blog/new-in-chrome-94/index.md
Labels: cla: yes

#1488 Fix missing link in NIC94 post
  site/en/blog/new-in-chrome-94/index.md
Labels: cla: yes

#1489 CUJ Tweaks for I can roll out new versions of my extension progressively
  site/en/docs/webstore/update/index.md
Labels: extensions, cla: yes

#1492 Add note about weird RegEx implementation
  site/en/docs/devtools/console/reference/index.md
Labels: cla: yes

#1365 Move media updates post from WebFu
  site/en/blog/media-updates-in-chrome-58/index.md
  site/en/blog/media-updates-in-chrome-61/index.md
  site/en/blog/media-updates-in-chrome-62/index.md
  site/en/blog/media-updates-in-chrome-63-64/index.md
  site/en/blog/media-updates-in-chrome-69/index.md
  site/en/blog/media-updates-in-chrome-70/index.md
  site/en/blog/media-updates-in-chrome-73/index.md
  site/en/blog/media-updates-in-chrome-75/index.md
Labels: cla: yes

#1494 [devtools] Update typo
  site/en/blog/new-in-devtools-95/index.md
  site/es/blog/new-in-devtools-95/index.md
  site/ja/blog/new-in-devtools-95/index.md
  site/ko/blog/new-in-devtools-95/index.md
  site/pt/blog/new-in-devtools-95/index.md
  site/ru/blog/new-in-devtools-95/index.md
  site/zh/blog/new-in-devtools-95/index.md
Labels: reviewers: devtools, cla: yes

#1487 Added Privacy Sandbox FAQ
  site/_data/docs/privacy-sandbox/toc.yml
  site/en/docs/privacy-sandbox/faq/index.md
Labels: cla: yes

#1496 MV2 support/sunset timeline and its introduction page
  site/_data/authorsData.json
  site/_data/docs/extensions/toc.yml
  site/_data/i18n/authors.yaml
  site/en/blog/mv2-transition/index.md
  site/en/docs/extensions/mv3/index.md
  site/en/docs/extensions/mv3/mv2-sunset/index.md
Labels: cla: yes

#1483 Add documentation for the "declarativeNetRequestWithHostAccess" permission.
  site/en/docs/extensions/reference/declarativeNetRequest/index.md
Labels: cla: yes

#1484 Translate new-in-devtools-95 in Japanese
  site/_includes/partials/devtools/ja/whats-new.md
  site/ja/blog/new-in-devtools-95/index.md
Labels: cla: yes, devtools-translate

#1503 Added "what's new" entry for MV2 timeline
  site/en/docs/extensions/mv3/mv2-sunset/index.md
  site/en/docs/extensions/whatsnew/index.md
Labels: cla: yes

#1500 Fix a broken link
  site/ja/blog/new-in-devtools-95/index.md
Labels: cla: yes

#1499 [devtools-translate] Portuguese - What's New in DevTools (Chrome 95)
  site/_includes/partials/devtools/pt/whats-new.md
  site/pt/blog/new-in-devtools-95/index.md
Labels: cla: yes, devtools-translate

#1440 Chrome user device characteristics report
  site/_data/authorsData.json
  site/_data/i18n/authors.yaml
  site/_data/i18n/tags.yml
  site/_data/supportedTags.json
  site/en/blog/device-characteristics/index.md
Labels: cla: yes

#1504 Correct deprecation timeline.
  site/en/blog/deps-rems-95/index.md
Labels: cla: yes

#1505 Adding pwa summit registration banner
  site/_data/banner.yml
Labels: cla: yes

#1516 Correct publication date
  site/en/blog/device-characteristics/index.md
Labels: cla: yes

#1490 CUJ Tweaks for I can manage a test version of my item.
  site/en/docs/webstore/cws-dashboard-distribution/index.md
Labels: extensions, cla: yes

#1518 Betelgeuse package of policy updates
  site/en/blog/policy-update-kwspam-and-circumvention/index.md
  site/en/docs/webstore/program_policies/index.md
  site/en/docs/webstore/spam-faq/index.md
Labels: cla: yes

#1507 Fix typo on '/docs/extensions/mv3/'
  site/en/docs/extensions/mv3/index.md
Labels: cla: yes

#1511 [devtools-translate] Spanish - What's new in DevTools (Chrome 95)
  site/es/blog/new-in-devtools-95/index.md
Labels: cla: yes, devtools-translate

#1495 Update index.md
  site/en/docs/android/custom-tabs/best-practices/index.md
Labels: cla: yes

#1479 Updated doc to mention https requirement
  site/en/docs/android/trusted-web-activity/receive-payments-play-billing/index.md
Labels: cla: yes

#1524 [devtools] Update Chinese What's new
  site/_includes/partials/devtools/es/whats-new.md
  site/_includes/partials/devtools/zh/whats-new.md
  site/es/blog/new-in-devtools-95/index.md
  site/zh/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes

#1517 UA-CH FAQ
  site/en/docs/privacy-sandbox/faq/index.md
Labels: cla: yes

#1520 Updated FLEDGE flag information
  site/en/docs/privacy-sandbox/fledge/index.md
Labels: cla: yes

#1527 Blog for "Progress in the Privacy Sandbox (September 2021)"
  site/_data/i18n/common.yml
  site/en/blog/progress-in-the-privacy-sandbox-2021-09/index.md
Labels: cla: yes

#1532 Updated Privacy Sandbox FAQ
  site/en/docs/privacy-sandbox/faq/index.md
Labels: cla: yes

#1485 Update manifest and page to be MV3 on '/mv3/tut_oauth/'
  site/en/docs/extensions/mv3/tut_oauth/index.md
Labels: cla: yes
