Repository GoogleChrome/developer.chrome.com, pull requests merged in 2021-08, with the labels that each got.

#1077 Fix document error.
  site/en/docs/extensions/mv3/content_scripts/index.md
Labels: cla: yes

#1078 Fix typo
  site/en/blog/new-in-devtools-93/index.md
Labels: cla: yes

#1041 CUJ Tweaks for becoming a Chrome Web Store Developer
  site/en/docs/webstore/about_webstore/index.md
  site/en/docs/webstore/faq/index.md
  site/en/docs/webstore/group-publishers/index.md
  site/en/docs/webstore/publish/index.md
  site/en/docs/webstore/register/index.md
Labels: cla: yes

#1042 blog post for run on login
  site/_data/authorsData.json
  site/en/blog/run-on-login/index.md
Labels: cla: yes

#1083 Update incorrect anchor link
  site/en/docs/webstore/update/index.md
Labels: cla: yes

#1082 Remove mention of bubblewrap generating assetlinks.json
  site/en/docs/android/trusted-web-activity/quick-start/index.md
Labels: cla: yes

#1079 Fix typo in description field of WebDriver BiDi article
  site/en/blog/webdriver-bidi/index.md
Labels: cla: yes

#988 Update externally_connectable example to use HTTPS
  site/en/docs/extensions/mv3/messaging/index.md
Labels: cla: yes

#994 Add updated date to CWS best practices page
  site/en/docs/webstore/best_practices/index.md
Labels: cla: yes

#662 Correct out-of-date info on manifest version page
  site/en/docs/extensions/mv3/manifest/manifest_version/index.md
Labels: cla: yes

#831 Minor tweaks and fixes
  site/en/docs/extensions/mv3/content_scripts/index.md
Labels: cla: yes

#1089 Small updates
  site/en/blog/coep-credentialless-origin-trial/index.md
  site/en/blog/cross-device-webotp/index.md
Labels: cla: yes

#1064 Add deprecations/removals article for 93.
  site/en/blog/deps-rems-93/index.md
Labels: cla: yes

#978 Added LambdaTest under Cloud-based emulators and simulators
  site/en/docs/devtools/device-mode/testing-other-browsers/index.md
Labels: cla: yes

#1086 fixes function: => func: in commands API
  site/en/docs/extensions/reference/commands/index.md
Labels: cla: yes

#1069 add reference page to percy, include 1600px screenshot
  .percy.js
Labels: cla: yes

#1085 remove multiple script support, fix link
  site/en/docs/extensions/mv3/background_pages/index.md
Labels: cla: yes

#1096 update poor link
  site/en/docs/extensions/mv2/hosting/index.md
  site/en/docs/extensions/mv3/hosting/index.md
Labels: cla: yes

#1094 Remove dup manifest version page
  server/env.js
  server/index.js
  server/redirect.js
  server/unique-redirect.js
  site/en/docs/extensions/mv2/manifest/manifest_version/index.md
Labels: cla: yes

#1099 Fix redirects code that is 500'ing
  package-lock.json
  package.json
  server/index.js
  server/redirect.js
  server/unique-redirect.js
  tsconfig.json
Labels: cla: yes

#1102 Update 2SV enforcement timeline
  site/en/blog/policy-update-2sv/index.md
  site/en/docs/extensions/whatsnew/index.md
Labels: cla: yes

#1097 Cleanup "Hosting" page
  site/en/docs/extensions/mv2/hosting/index.md
  site/en/docs/extensions/mv3/hosting/index.md
Labels: cla: yes

#1095 boop webdev-infra for imgix auto format
  package-lock.json
  package.json
  site/_includes/partials/meta.njk
  site/_shortcodes/Img.js
  site/_shortcodes/Video.js
Labels: cla: yes

#1093 Icon titles
  site/_data/i18n/common.yml
  site/_includes/macros/cards/featured-docs-card.njk
  site/_includes/macros/cards/featured-post-card.njk
  site/_includes/macros/cards/hero-card.njk
  site/_includes/macros/navigation-tree-sections.njk
  site/_includes/partials/breadcrumbs.njk
  site/_includes/partials/cookie-banner.njk
  site/_includes/partials/footer.njk
  site/_includes/partials/navigation-rail.njk
  site/_includes/partials/navigation-tree.njk
  site/_includes/partials/pagination.njk
  site/_includes/partials/top-nav.njk
Labels: cla: yes

#1103 2SV post metadata typo fix
  site/en/blog/policy-update-2sv/index.md
Labels: extensions, cla: yes

#1104 fix hostnames - code.google.com/chrome
  server/env.js
  server/index.js
  server/plural-domain.js
  server/unknown-domain.js
Labels: cla: yes

#1080 CUJ Tweaks for Setting up my developer account
  site/en/docs/webstore/cws-dashboard-privacy/index.md
  site/en/docs/webstore/publish/index.md
Labels: extensions, cla: yes

#1040 Add sitemap.xml
  site/_data/helpers.js
  site/_data/lib/date.js
  site/sitemap.xml.njk
Labels: cla: yes

#1023 Add Simplified Chinese translations for What's New in DevTools M92
  site/_data/site.json
  site/zh/blog/new-in-devtools-92/index.md
Labels: reviewers: devtools, cla: yes

#1035 Translation es new in devtools 92
  site/_data/authorsData.json
  site/es/blog/new-in-devtools-92/index.md
Labels: reviewers: devtools, cla: yes

#1120 [devtools] Update hero image
  site/en/blog/new-in-devtools-93/index.md
Labels: reviewers: devtools, cla: yes

#962 Added "attribution reporting: a primer" post
  site/_data/authorsData.json
  site/en/docs/privacy-sandbox/attribution-reporting-introduction/index.md
  site/en/docs/privacy-sandbox/status/index.md
Labels: cla: yes

#1126 Fixed date
  site/en/docs/privacy-sandbox/attribution-reporting-introduction/index.md
Labels: cla: yes

#950 Fix broken link in Tabs API docs
  site/en/docs/extensions/reference/tabs/index.md
Labels: cla: yes

#1105 move anchor icon to left side of heading
  package-lock.json
  package.json
  site/_filters/toc.js
  site/_plugins/markdown.js
  site/_scss/blocks/_heading-link.scss
  site/_scss/globals/extends/_heading-link.scss
Labels: cla: yes

#1134 show manifest keys required for API
  package-lock.json
  package.json
  site/_includes/layouts/namespace-reference.njk
Labels: cla: yes

#1129 Update executeScript snippets in migration guide
  site/en/docs/extensions/mv3/intro/mv3-migration/index.md
Labels: extensions, cla: yes

#1135 Update CSP link to be a little better
  site/en/docs/extensions/mv3/manifest/index.md
Labels: cla: yes

#1127 Restructure attribution reporting content
  site/en/docs/privacy-sandbox/attribution-reporting-introduction/index.md
  site/en/docs/privacy-sandbox/attribution-reporting/index.md
  site/en/docs/privacy-sandbox/status/index.md
Labels: cla: yes

#1136 update fileBrowserHandler docs
  site/en/docs/extensions/reference/fileBrowserHandler/index.md
Labels: cla: yes

#1130 Added origin-trial-troubleshooting
  site/en/blog/origin-trial-troubleshooting/index.md
Labels: cla: yes

#1108 [CWS CUJs] Update dates
  site/en/docs/extensions/mv3/getstarted/index.md
  site/en/docs/webstore/group-publishers/index.md
  site/en/docs/webstore/register/index.md
Labels: chore, extensions, cla: yes

#1140 blackbox => "ignore script"
  redirects.yaml
  site/_data/docs/devtools/toc.yml
  site/en/blog/new-in-devtools-66/index.md
  site/en/blog/new-in-devtools-70/index.md
  site/en/docs/devtools/javascript/ignore-chrome-extension-scripts/index.md
  site/en/docs/devtools/javascript/reference/index.md
Labels: cla: yes

#1143 don't crash on bad authors
  site/_includes/macros/card-authors.njk
Labels: cla: yes

#1137 replace 'foo.html' => 'foo/' in checks for redirects
  server/unique-redirect.js
Labels: cla: yes

#1139 rewrites the 'user_interface' page for MV3
  site/en/docs/extensions/mv3/user_interface/index.md
Labels: cla: yes

#1152 Add link to CWS dashboard.
  site/_data/docs/webstore/toc.yml
  site/_data/i18n/docs/webstore.yml
Labels: cla: yes

#1151 Added First-Party sets video
  site/en/docs/privacy-sandbox/first-party-sets/index.md
Labels: cla: yes

#1150 Updated privacy-sandbox.svg
  site/_static/images/project/privacy-sandbox.svg
Labels: cla: yes

#1124 New "make a great listing" page
  site/_data/docs/webstore/toc.yml
  site/en/docs/webstore/best_listing/index.md
  site/en/docs/webstore/best_practices/index.md
  site/en/docs/webstore/cws-dashboard-listing/index.md
  site/en/docs/webstore/images/index.md
Labels: extensions, cla: yes

#1145 CUJ Tweaks for I can terminate my relationship with Google
  site/en/docs/webstore/account-deletion/index.md
  site/en/docs/webstore/faq/index.md
Labels: P2, extensions, cla: yes

#1154 Removes mention of Action API for MV2
  site/en/docs/extensions/mv3/intro/mv3-migration/index.md
  site/en/docs/extensions/reference/tabs/index.md
Labels: cla: yes

#1149 migrate SW page update re: fetch and module import
  redirects.yaml
  site/en/docs/extensions/mv3/manifest/index.md
  site/en/docs/extensions/mv3/migrating_to_service_workers/index.md
  site/en/docs/extensions/mv3/service_workers/index.md
  site/en/docs/extensions/mv3/xhr/index.md
Labels: cla: yes

#1125 CUJ Tweaks for I want to Publish my item
  site/en/docs/webstore/cws-dashboard-distribution/index.md
  site/en/docs/webstore/cws-dashboard-listing/index.md
  site/en/docs/webstore/cws-dashboard-privacy/index.md
  site/en/docs/webstore/images/index.md
  site/en/docs/webstore/publish/index.md
Labels: P2, extensions, cla: yes

#1159 always render 'authors'
  site/_includes/macros/cards/blog-card.njk
Labels: cla: yes

#1160 fix < > to &lt; &gt; on match_patterns page
  site/en/docs/extensions/mv2/match_patterns/index.md
  site/en/docs/extensions/mv3/match_patterns/index.md
Labels: cla: yes

#1161 Update index.md - Amends typo futher to further
  site/en/docs/extensions/mv3/service_workers/index.md
Labels: cla: yes

#1165 fix bad line highlight on SW module import example
  site/en/docs/extensions/mv3/service_workers/index.md
Labels: cla: yes

#1155 [devtools-blog] Add CSS Grid tooling blog for DevTools
  site/en/blog/css-grid-tooling/index.md
Labels: reviewers: devtools, cla: yes

#1170 Add Changhao as DevTools blog post author
  site/_data/authorsData.json
Labels: reviewers: devtools, cla: yes

#1176 Troubleshooting polish
  site/en/docs/webstore/troubleshooting/index.md
Labels: cla: yes

#1043 Add Android for Web developers page
  site/_data/authorsData.json
  site/_data/docs/android/toc.yml
  site/en/docs/android/trusted-web-activity/android-for-web-devs/index.md
  site/en/docs/android/trusted-web-activity/quick-start/index.md
Labels: cla: yes

#1180 Fix function to func
  site/en/docs/extensions/reference/scripting/index.md
Labels: cla: yes

#1181 Describe about the args property
  site/en/docs/extensions/reference/scripting/index.md
Labels: cla: yes

#850 Add deprecations and removals for Chrome 92.
  site/en/blog/deps-rems-92/index.md
Labels: cla: yes

#1182 add "Developers" to the sidebar, <use> other SVG
  package-lock.json
  package.json
  site/_includes/macros/icon.njk
  site/_includes/partials/navigation-rail.njk
  site/_includes/partials/top-nav.njk
  site/_scss/blocks/_logo.scss
  site/_scss/blocks/_top-nav.scss
  site/_scss/main.scss
Labels: cla: yes

#1174 Tweaks to adding blog post
  site/en/docs/handbook/how-to/add-a-blog-post/index.md
Labels: cla: yes

#1175 Shared element transition article
  site/en/blog/shared-element-transitions-for-spas/index.md
Labels: cla: yes

#1221 Fixed path for webstore links
  site/en/docs/webstore/cws-enterprise/index.md
Labels: cla: yes

#1166 add aside reminding users they can't script chrome://extensions
  site/en/docs/extensions/mv2/getstarted/index.md
  site/en/docs/extensions/mv3/getstarted/index.md
Labels: cla: yes

#1147 update devtools network reference for modern Chrome
  site/en/docs/devtools/network/reference/index.md
Labels: cla: yes

#1186 Fix CSS syntax
  site/en/docs/extensions/reference/scripting/index.md
Labels: cla: yes

#1168 misc docs fixes
  site/_scss/blocks/_devtools.scss
  site/_scss/main.scss
  site/en/docs/apps/manifest/externally_connectable/index.md
  site/en/docs/devtools/console/utilities/index.md
  site/en/docs/devtools/css/index.md
  site/en/docs/devtools/javascript/index.md
  site/en/docs/extensions/mv3/content_scripts/index.md
  site/en/docs/extensions/mv3/faq/index.md
  site/en/docs/extensions/mv3/manifest/index.md
  site/en/docs/extensions/mv3/match_patterns/index.md
  site/en/docs/extensions/mv3/permission_warnings/index.md
  site/en/docs/extensions/mv3/sandboxingEval/index.md
  site/en/docs/extensions/mv3/settings_override/index.md
  site/en/docs/extensions/reference/bookmarks/index.md
  site/en/docs/extensions/reference/browserAction/index.md
  site/en/docs/extensions/reference/browsingData/index.md
  site/en/docs/extensions/reference/contentSettings/index.md
  site/en/docs/extensions/reference/declarativeNetRequest/index.md
  site/en/docs/extensions/reference/declarativeWebRequest/index.md
  site/en/docs/extensions/reference/experimental/index.md
  site/en/docs/extensions/reference/permissions/index.md
  site/en/docs/extensions/reference/wallpaper/index.md
  site/en/docs/multidevice/android/overview/index.md
  site/en/docs/webstore/faq/index.md
Labels: cla: yes

#1225 add feeds for all tags
  site/_collections/feeds.js
  site/_collections/tags.js
  site/_data/docs/handbook/toc.yml
  site/_data/i18n/tags.yml
  site/_includes/icons/rss.svg
  site/_includes/layouts/base.njk
  site/_includes/layouts/tag-landing.njk
  site/_includes/partials/breadcrumbs-tag.njk
  site/_utils/tag-11tydata.js
  site/en/docs/handbook/style-guide/a.jpg
  site/en/docs/handbook/style-guide/index.njk
  site/feed.njk
Labels: cla: yes

#1148 render markdown, strip html tags in indexing
  .eleventy.js
  algolia.js
  cloud-secrets.js
  package-lock.json
  package.json
  site/_collections/algolia.js
  site/_collections/feeds.js
  site/_collections/tags.js
  site/_js/web-components/search-box.js
  site/_scss/blocks/_search-box.scss
  site/_utils/drafts.js
  tsconfig.json
  types/11ty/collection-item.d.ts
Labels: cla: yes

#1169 Breadcrumbs fixes
  site/_data/i18n/tags.yml
  site/_data/lib/links.js
  site/_data/supportedTags.json
  site/_includes/layouts/blog-landing.njk
  site/_includes/layouts/docs-landing.njk
  site/_includes/layouts/tag-landing.njk
  site/_includes/layouts/tags-landing.njk
  site/_includes/macros/tag.njk
  site/_includes/partials/breadcrumbs-tag.njk
  site/_includes/partials/breadcrumbs.njk
  site/_includes/partials/title-bar.njk
  site/_scss/blocks/_breadcrumbs.scss
  site/_scss/blocks/_share-button.scss
  site/_scss/globals/extends/_navigation.scss
Labels: cla: yes

#1179 hoist /overview/ pages up where there's no parent index
  redirects.yaml
  site/_data/docs/android/toc.yml
  site/_data/docs/multidevice/toc.yml
  site/en/docs/android/custom-tabs/headers/index.md
  site/en/docs/android/custom-tabs/index.md
  site/en/docs/android/trusted-web-activity/index.md
  site/en/docs/android/trusted-web-activity/quick-start/index.md
  site/en/docs/multidevice/android/index.md
  site/en/docs/multidevice/faq/index.md
  site/en/docs/multidevice/overview/index.md
  site/en/docs/multidevice/user-agent/index.md
  site/en/docs/multidevice/webview/index.md
  site/en/docs/webstore/payments-iap/cws-dd-otp-item.png
  site/en/docs/webstore/payments-iap/purchase-flow-1.png
Labels: cla: yes

#1231 [Shared element transition API article] Add link to CSS Containment article
  site/en/blog/shared-element-transitions-for-spas/index.md
Labels: cla: yes

#1230 Updated origin trial details and wording
  site/en/docs/privacy-sandbox/floc/index.md
  site/en/docs/privacy-sandbox/status/index.md
  site/en/docs/privacy-sandbox/trust-tokens/index.md
Labels: cla: yes

#1177 CUJ Tweaks for I want to be aware of any action required by Google
  site/en/docs/webstore/group-publishers/index.md
  site/en/docs/webstore/publish/index.md
Labels: P2, extensions, cla: yes

#1228 Fixed broken links and typos
  site/en/docs/extensions/mv3/user_interface/index.md
Labels: cla: yes

#1115 Add thumbnail support
  site/_data/site.json
  site/_includes/macros/cards/blog-card.njk
  site/_includes/macros/cards/featured-post-card.njk
  site/_includes/partials/meta.njk
  site/en/blog/_example/index.md
Labels: cla: yes

#1237 Update translation details
  site/zh/blog/new-in-devtools-92/index.md
Labels: reviewers: devtools, cla: yes

#1229 drop needless supportedTags.json file
  .pullapprove.yml
  site/_collections/tags.js
  site/_data/i18n/tags.yml
  site/_data/supportedTags.json
  site/_includes/macros/tag.njk
  site/_utils/tag-11tydata.js
  site/_utils/tags-11tydata.js
  site/en/blog/_example/index.md
  site/en/docs/_example/my-first-doc/index.md
  site/en/docs/handbook/how-to/add-a-tag/index.md
  types/site/_collections/tags.d.ts
Labels: cla: yes

#1243 add releases card on home page
  site/_data/chrome.js
  site/_data/i18n/common.yml
  site/_includes/layouts/home.njk
  site/_includes/layouts/releases-landing.njk
  site/_includes/macros/cards/releases-card.njk
  site/_scss/blocks/_release-card.scss
  site/_scss/main.scss
  tests/site/_data/chrome.js
  types/site/_data/chrome.d.ts
Labels: cla: yes

#1236 [devtools-translate] Add Simplified Chinese translations for What's New in DevTools M93
  site/_data/authorsData.json
  site/zh/blog/new-in-devtools-93/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1235 devtools storage cleanups
  site/en/docs/devtools/storage/applicationcache/index.md
  site/en/docs/devtools/storage/cache/index.md
  site/en/docs/devtools/storage/cookies/index.md
  site/en/docs/devtools/storage/indexeddb/index.md
  site/en/docs/devtools/storage/localstorage/index.md
  site/en/docs/devtools/storage/sessionstorage/index.md
  site/en/docs/devtools/storage/websql/index.md
Labels: cla: yes

#1254 Ignore Intellij project settings folder
  .gitignore
Labels: cla: yes

#1256 [devtools] What's new in DevTools (Chrome 94)
  site/_includes/partials/devtools/whats-new.md
  site/en/blog/new-in-devtools-94/index.md
Labels: reviewers: devtools, cla: yes

#1224 Manage your CWS item
  site/_data/docs/webstore/toc.yml
  site/en/docs/webstore/manage/index.md
Labels: extensions, cla: yes

#1184 RenderingNG data structures
  site/_data/authorsData.json
  site/en/blog/renderingng-data-structures/index.md
Labels: cla: yes

#1223 Update image for rendering pipeline
  site/en/blog/renderingng-architecture/index.md
Labels: cla: yes

#1264 Update image for immutable fragment tree
  site/en/blog/renderingng-data-structures/index.md
Labels: cla: yes

#1262 Fixed repeated text about 'locally, on the user's device'
  site/en/docs/privacy-sandbox/fledge/index.md
Labels: cla: yes

#1261 Fixed broken links
  site/en/docs/privacy-sandbox/attribution-reporting/index.md
Labels: cla: yes

#1260 Don't track pyenv version file
  .gitignore
Labels: cla: yes

#1258 Fix link in first aside
  site/en/docs/webstore/group-publishers/index.md
Labels: cla: yes

#1269 [devtools-blog] Fix broken link
  site/_includes/partials/devtools/whats-new.md
Labels: reviewers: devtools, cla: yes

#1277 Update RenderingNG arch to forward-link
  site/en/blog/renderingng-architecture/index.md
Labels: cla: yes

#1276 Update RenderingNG post to forward-link
  site/en/blog/renderingng/index.md
Labels: cla: yes

#1302 [devtools] Add application cache documentation
  site/en/docs/devtools/storage/applicationcache/index.md
Labels: reviewers: devtools, cla: yes

#1306 Add a DevTools translate issue template
  .github/ISSUE_TEMPLATE/devtools_translate.md
Labels: cla: yes

#1288 Polish CWS dashboard privacy page
  site/en/docs/webstore/cws-dashboard-privacy/index.md
Labels: cla: yes

#1300 [devtools] Add placeholder for DevTools translations
  site/_includes/partials/devtools/es/reach-out.md
  site/_includes/partials/devtools/ja/banner.md
  site/_includes/partials/devtools/ja/reach-out.md
  site/_includes/partials/devtools/ja/whats-new.md
  site/_includes/partials/devtools/ko/banner.md
  site/_includes/partials/devtools/ko/reach-out.md
  site/_includes/partials/devtools/ko/whats-new.md
  site/_includes/partials/devtools/pt/banner.md
  site/_includes/partials/devtools/pt/reach-out.md
  site/_includes/partials/devtools/pt/whats-new.md
  site/_includes/partials/devtools/ru/reach-out.md
Labels: cla: yes, devtools-translate

#1316 Progress in the Privacy Sandbox August 2021
  site/_data/i18n/tags.yml
  site/en/blog/progress-in-the-privacy-sandbox-2021-08/index.md
Labels: cla: yes

#1317 fix cookie banner
  site/_includes/layouts/base.njk
  site/_includes/partials/script.js
Labels: cla: yes

#1321 Correct duplicated text in "Progress in the Privacy Sandbox (August 2021)" blog
  site/en/blog/progress-in-the-privacy-sandbox-2021-08/index.md
Labels: cla: yes

#1327 feat(tags): show tag links in article footers, fixes #1308
  site/_includes/layouts/blog-post.njk
  site/_includes/macros/cards/blog-card.njk
  site/_includes/partials/tags.njk
Labels: cla: yes
