Repository GoogleChrome/developer.chrome.com, pull requests merged in 2021-07, with the labels that each got.

#943 Add examples to Command API page
  site/en/docs/extensions/reference/commands/index.md
Labels: cla: yes, extensions

#946 Add VideoNG as a project
  site/en/blog/renderingng/index.md
Labels: cla: yes

#857 Replaces usage of CCT deprecated APIs
  site/en/docs/android/custom-tabs/best-practices/index.md
  site/en/docs/android/custom-tabs/integration-guide/index.md
Labels: cla: yes

#812 Minor tweaks to wording of Attribution Reporting article
  site/en/docs/privacy-sandbox/attribution-reporting/index.md
Labels: cla: yes

#756 [devtools-blog] Update APCA explanation
  site/en/blog/new-in-devtools-89/index.md
Labels: cla: yes, reviewers: devtools

#965 Changed incorrect property func to function
  site/en/docs/extensions/reference/commands/index.md
Labels: cla: yes

#909 Chromium Chronicle 22
  site/en/blog/chromium-chronicle-22/index.md
Labels: cla: yes

#998 fix(runtime): fix typo in code, fixes #975
  site/en/docs/extensions/reference/runtime/index.md
Labels: cla: yes

#995 set X-Frame-Options and update CSP header
  server/index.js
Labels: cla: yes

#999 [devtools] Update What's new in DevTools 92 video
  site/en/blog/new-in-devtools-92/index.md
Labels: cla: yes, reviewers: devtools

#990 Enhance RenderingNG document
  site/en/blog/renderingng/index.md
Labels: cla: yes

#981 Add missing property in code example
  site/en/docs/extensions/reference/runtime/index.md
Labels: cla: yes, extensions

#901 Add share button
  site/_includes/layouts/blog-post.njk
  site/_includes/layouts/doc-post.njk
  site/_includes/partials/breadcrumbs.njk
  site/_includes/partials/title-bar.njk
  site/_js/main.js
  site/_js/web-components/share-button.js
  site/_scss/blocks/_share-button.scss
  site/_scss/main.scss
Labels: cla: yes

#1016 Remove cookies
  site/_js/web-components/language-select.js
Labels: cla: yes

#1024 Fix mangled language code
  site/ja/ja.11tydata.js
Labels: cla: yes

#1025 Remove underscore from web component name
  site/_js/web-components/language-select.js
Labels: cla: yes

#1026 Bump webdev-infra version
  package-lock.json
  package.json
Labels: cla: yes

#1027 Remove extra trailing comma in manifest.json
  site/en/docs/extensions/reference/action/index.md
Labels: cla: yes

#1021 Fix: missing apostrophe in payments docs
  site/en/docs/android/trusted-web-activity/receive-payments-play-billing/index.md
Labels: cla: yes

#984 [Introducing chrome.scripting] fixed fetch url typo of Manifest V3 example
  site/en/blog/crx-scripting-api/index.md
Labels: cla: yes

#968 Incorrect usage the passed argument to the listener
  site/en/docs/extensions/reference/commands/index.md
Labels: cla: yes

#959 Fix opt_extraInfoSpec typo in webRequest docs
  site/en/docs/extensions/reference/webRequest/index.md
Labels: cla: yes

#997 CUJ Tweaks for Creating a MV3 Chrome Extension
  site/en/docs/extensions/mv3/getstarted/index.md
Labels: P2, cla: yes, extensions

#1028 Update Single Purpose FAQ
  redirects.yaml
  site/en/docs/extensions/mv2/single_purpose/index.md
  site/en/docs/extensions/mv3/single_purpose/index.md
Labels: cla: yes

#992 Fix match pattern typos in example configs in Security page
  site/en/docs/extensions/mv3/security/index.md
Labels: cla: yes

#991 Correct the path to creating a release
  site/en/docs/android/trusted-web-activity/quick-start/index.md
Labels: cla: yes

#907 Update manifest_version page to suggest using v3
  site/en/docs/extensions/mv3/manifest/manifest_version/index.md
Labels: cla: yes

#979 Fix invalid xmlns for gupdate tag
  site/en/docs/extensions/mv2/linux_hosting/index.md
  site/en/docs/extensions/mv3/linux_hosting/index.md
Labels: cla: yes

#1013 RenderingNG architecture post
  site/en/blog/renderingng-architecture/index.md
Labels: cla: yes

#1009 add chromeOS warning as a pill
  site/_includes/macros/render-type.njk
Labels: cla: yes

#1031 [devtools] Fix typo
  site/en/blog/new-in-devtools-92/index.md
Labels: cla: yes, reviewers: devtools

#1032 [devtools] Remove deprecated docs
  site/en/docs/devtools/javascript/reference/index.md
Labels: cla: yes, reviewers: devtools

#1038 Remove js masonry layout. Simplify with flexbox.
  site/_includes/layouts/home.njk
  site/_includes/macros/cards/featured-docs-card.njk
  site/_includes/macros/cards/featured-post-card.njk
  site/_includes/macros/cards/featured-tweet-card.njk
  site/_includes/partials/featured-cds-card.njk
  site/_includes/partials/report-a-bug.njk
  site/_scss/blocks/_masonry-grid.scss
  site/_scss/main.scss
Labels: cla: yes

#1033 makes desktop toc sticky + highlight top link
  site/_includes/partials/toc-side.njk
  site/_js/main.js
  site/_js/web-components/toc-active.js
  site/_scss/blocks/_toc.scss
  site/_scss/globals/_mixins.scss
  site/_scss/main.scss
  site/_scss/utilities/_scrollbars.scss
Labels: cla: yes

#1049 [devtools] What's new in DevTools 93
  site/en/blog/new-in-devtools-93/index.md
  site/en/docs/devtools/updates/index.md
Labels: cla: yes, reviewers: devtools

#1020 Chromium Chronicle 23
  site/en/blog/chromium-chronicle-23/index.md
Labels: cla: yes

#1044 Cross device WebOTP
  site/_data/authorsData.json
  site/en/blog/cross-device-webotp/index.md
Labels: cla: yes

#1050 Fix video on new WebOTP post
  site/en/blog/cross-device-webotp/index.md
Labels: cla: yes

#1052 WebOTP post video fix
  site/en/blog/cross-device-webotp/index.md
Labels: cla: yes

#1056 chore(dependencies): update infra dependency
  package-lock.json
  package.json
  site/_shortcodes/Img.js
  site/_shortcodes/Video.js
Labels: cla: yes

#1054 Minor fixes
  site/_data/authorsData.json
  site/en/blog/cross-device-webotp/index.md
Labels: cla: yes

#1055 Fix typo and update description in authorsData.json
  site/_data/authorsData.json
Labels: cla: yes

#1046 Adds "Wasm modules sharing restricted to same-origin" article
  site/en/blog/wasm-module-sharing-restricted-to-same-origin/index.md
Labels: cla: yes

#1058 Update featured image on x-device webotp article
  site/en/blog/cross-device-webotp/index.md
Labels: cla: yes

#1045 Adds COEP: credentialless article
  site/en/blog/coep-credentialless-origin-trial/index.md
Labels: cla: yes

#1059 [devtools-blog] WebDriver BiDi - The future of cross-browser automation
  site/en/blog/webdriver-bidi/index.md
Labels: cla: yes, reviewers: devtools

#1061 Added video to Trust Tokens article
  site/en/docs/privacy-sandbox/overview/index.md
  site/en/docs/privacy-sandbox/trust-tokens/index.md
Labels: cla: yes

#1063 Update an illustration
  site/en/blog/coep-credentialless-origin-trial/index.md
Labels: cla: yes

#919 Domain publishing
  site/_data/docs/webstore/toc.yml
  site/en/docs/webstore/cws-dashboard-distribution/index.md
  site/en/docs/webstore/cws-enterprise/index.md
Labels: cla: yes, extensions

#1067 Revert "makes desktop toc sticky + highlight top link (#1033)"
  site/_includes/partials/toc-side.njk
  site/_js/main.js
  site/_js/web-components/toc-active.js
  site/_scss/blocks/_toc.scss
  site/_scss/globals/_mixins.scss
  site/_scss/main.scss
  site/_scss/utilities/_scrollbars.scss
Labels: cla: yes

#1068 Revert revert the TOC changes
  site/_includes/layouts/doc-post.njk
  site/_includes/layouts/namespace-reference.njk
  site/_includes/layouts/reference-landing.njk
  site/_includes/partials/toc-side.njk
  site/_js/main.js
  site/_js/web-components/toc-active.js
  site/_scss/blocks/_post.scss
  site/_scss/blocks/_toc.scss
  site/_scss/globals/_mixins.scss
  site/_scss/main.scss
  site/_scss/utilities/_scrollbars.scss
Labels: cla: yes
