Repository GoogleChrome/developer.chrome.com, pull requests merged in 2021-11, with the labels that each got.

#1657 [devtools-blog] Added one author
  site/_data/authorsData.json
  site/_data/i18n/authors.yaml
  site/en/blog/csp-issues/index.md
Labels: reviewers: devtools, cla: yes

#1645 Add Force Chrome major version to 100 in the UA string
  site/_data/authorsData.json
  site/_data/i18n/authors.yaml
  site/en/blog/force-major-version-to-100/index.md
Labels: cla: yes

#1660 Add alexandrawhite
  site/_data/authorsData.json
  site/_data/i18n/authors.yaml
Labels: cla: yes

#1656 write site build version
  gulp-tasks/write-version.js
  gulpfile.js
  tools/version/index.js
Labels: cla: yes

#1663 actually write version
  gulp-tasks/write-version.js
Labels: cla: yes

#1664 don't render comment again for top-level namespace
  site/_includes/macros/reference.njk
Labels: cla: yes

#1640 Update to Trust Tokens text
  site/en/docs/privacy-sandbox/overview/index.md
  site/en/docs/privacy-sandbox/trust-tokens/index.md
Labels: cla: yes

#1659 Update index.md
  site/en/docs/privacy-sandbox/faq/index.md
Labels: cla: yes

#1666 add version-check task which can kick off build
  .cloudbuild/version-check.yaml
  package-lock.json
  package.json
  version-check.js
Labels: cla: yes

#1670 correctly sync before check, throw on unhandled rejection
  .cloudbuild/version-check.yaml
  package.json
Labels: cla: yes

#1668 [devtools] Recorder documentation
  site/_data/docs/devtools/toc.yml
  site/en/docs/devtools/recorder/index.md
Labels: reviewers: devtools, cla: yes

#1575 Update index.md
  site/en/docs/privacy-sandbox/faq/index.md
Labels: cla: yes

#1658 Update link to OT / add link to feedback form
  site/en/blog/auto-dark-theme/index.md
Labels: cla: yes

#1674 [devtools] Add edit documentation
  site/en/docs/devtools/recorder/index.md
Labels: reviewers: devtools, cla: yes

#1643 Fix Shared Storage repo link
  site/en/docs/privacy-sandbox/faq/index.md
Labels: cla: yes

#1675 [devtools] Add temporarily video - recorder
  site/en/docs/devtools/recorder/index.md
Labels: reviewers: devtools, cla: yes

#1676 CDS21 update for Privacy Sandbox
  site/_data/docs/privacy-sandbox/toc.yml
  site/en/docs/privacy-sandbox/cds21-update/index.md
Labels: cla: yes, docs

#1679 [Recorder article] Minor corrections
  site/en/docs/devtools/recorder/index.md
Labels: reviewers: devtools, cla: yes

#1686 Fix recorder doc typo
  site/en/docs/devtools/recorder/index.md
Labels: reviewers: devtools, cla: yes

#1687 [devtools] Fix typo
  site/en/docs/devtools/recorder/index.md
Labels: reviewers: devtools, cla: yes

#1665 Translate "Getting Started in Chrome's Origin Trials" into Japanese
  site/ja/blog/origin-trials/index.md
Labels: cla: yes

#1688 FAQ clean up
  site/en/docs/privacy-sandbox/faq/index.md
Labels: cla: yes, docs

#1681 Fix external data changing every time
  external/build/lib/dts-parse.js
Labels: cla: yes

#1692 mark missing params as optional
  external/build/lib/dts-parse.js
  tests/external/types.js
Labels: cla: yes

#1690 Adds more workbox docs
  site/_data/docs/workbox/toc.yml
  site/_data/i18n/docs/workbox.yml
  site/_scss/blocks/_tabs.scss
  site/en/docs/workbox/app-shell-model/index.md
  site/en/docs/workbox/caching-strategies-overview/index.md
  site/en/docs/workbox/different-architectures/index.md
  site/en/docs/workbox/framework-integrations/index.md
  site/en/docs/workbox/improving-development-experience/index.md
  site/en/docs/workbox/navigation-preload/index.md
  site/en/docs/workbox/precaching-dos-and-donts/index.md
  site/en/docs/workbox/precaching-with-workbox/index.md
  site/en/docs/workbox/remove-buggy-service-workers/index.md
  site/en/docs/workbox/service-worker-deployment/index.md
  site/en/docs/workbox/service-worker-lifecycle/index.md
  site/en/docs/workbox/the-ways-of-workbox/index.md
  site/en/docs/workbox/troubleshooting-and-logging/index.md
  site/en/docs/workbox/using-workbox-without-precaching/index.md
  site/en/docs/workbox/what-is-workbox/index.md
Labels: cla: yes, docs

#1696 [devtools] Fix recorder doc typos
  site/en/docs/devtools/recorder/index.md
Labels: reviewers: devtools, cla: yes

#1703 Enable wdi banner
  site/_data/banner.yml
Labels: cla: yes

#1609 DNR fix bad example: https should be http
  site/en/docs/extensions/reference/declarativeNetRequest/index.md
Labels: cla: yes, docs

#1568 Add missing opening bracket to link on '/mv3/overview/'
  site/en/docs/extensions/mv3/overview/index.md
Labels: cla: yes

#1625 Fix digital-asset-links generator link
  site/en/docs/android/trusted-web-activity/integration-guide/index.md
Labels: cla: yes

#1677 Updated a status for an Attribution Reporting PAI feature
  site/en/docs/privacy-sandbox/attribution-reporting-introduction/index.md
Labels: cla: yes

#1661 [devtools-translate] Japanese - What's New in DevTools (Chrome 96)
  site/_includes/partials/devtools/ja/whats-new.md
  site/ja/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1678 Update instructions to get extension key
  site/en/docs/extensions/mv3/tut_oauth/index.md
Labels: extensions, cla: yes

#1705 Fix last updated date
  site/en/docs/webstore/program_policies/index.md
Labels: cla: yes

#1706 Fix typo
  site/en/docs/extensions/mv3/manifest/web_accessible_resources/index.md
Labels: cla: yes

#1704 Privacy Sandbox: Glossary clean and update
  site/en/docs/privacy-sandbox/glossary/index.md
Labels: cla: yes

#1635 [Privacy Sandbox] Added link to Troubleshooting Chrome's origin trials
  site/en/blog/origin-trials/index.md
Labels: cla: yes

#1715 Assorted minor cleanup
  .pullapprove.yml
  site/en/docs/apps/autoupdate/index.md
  site/en/docs/extensions/mv2/cross-origin-isolation/index.md
  site/en/docs/extensions/mv3/cross-origin-isolation/index.md
Labels: extensions, cla: yes

#1671 Clarify focus on promises in extensions APIs, cleanup
  site/en/docs/extensions/mv3/manifest/index.md
  site/en/docs/extensions/mv3/promises/index.md
Labels: extensions, cla: yes

#1662 [devtools-translate] Spanish - What's New in DevTools (Chrome 96)
  site/es/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: no, devtools-translate

#1720 [devtools-blog] Update WNDT 96
  site/_includes/partials/devtools/en/whats-new.md
  site/_includes/partials/devtools/es/whats-new.md
  site/_includes/partials/devtools/ja/whats-new.md
  site/en/blog/new-in-devtools-96/index.md
  site/es/blog/new-in-devtools-96/index.md
  site/ja/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes

#1710 [devtools-translate] Chinese - What's New in DevTools (Chrome 96)
  site/_includes/partials/devtools/zh/whats-new.md
  site/zh/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1721 [devtools-blog] Update WNDT 96
  site/_includes/partials/devtools/en/whats-new.md
  site/_includes/partials/devtools/ja/whats-new.md
  site/_includes/partials/devtools/zh/whats-new.md
  site/es/blog/new-in-devtools-96/index.md
  site/ja/blog/new-in-devtools-96/index.md
  site/zh/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes

#1641 CUJ Tweaks for I want to internationalize my extension
  site/en/docs/extensions/reference/i18n/index.md
  site/en/docs/webstore/i18n/index.md
Labels: extensions, cla: yes

#1712 [Privacy Sandbox] User Agent landing page
  site/_data/docs/privacy-sandbox/toc.yml
  site/en/docs/multidevice/user-agent/index.md
  site/en/docs/privacy-sandbox/status/index.md
  site/en/docs/privacy-sandbox/user-agent/index.md
Labels: cla: yes

#1680 Translate "What are third-party origin trials?" into Japanese
  site/ja/blog/third-party-origin-trials/index.md
Labels: reviewers: devtools, cla: yes

#1714 Extensions "What's New" page updates
  site/en/docs/extensions/whatsnew/index.md
Labels: extensions, cla: yes

#1708 [devtools-translate] Portuguese - What's New in DevTools (Chrome 96) #1618
  site/_includes/partials/devtools/pt/whats-new.md
  site/en/blog/new-in-devtools-96/index.md
  site/ja/blog/new-in-devtools-96/index.md
  site/pt/blog/new-in-devtools-96/index.md
  site/zh/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1638 [devtools-translate] Russian - What's New in DevTools (Chrome 96)
  site/_includes/partials/devtools/ru/whats-new.md
  site/ru/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1693 [devtools-translate] Korean - What's new in DevTools (Chrome 96)
  site/_includes/partials/devtools/ko/whats-new.md
  site/ko/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes, devtools-translate

#1722 [devtools-translate] Spanish - What's New in DevTools (Chrome 96)
  site/en/blog/new-in-devtools-96/index.md
  site/es/blog/new-in-devtools-96/index.md
  site/ja/blog/new-in-devtools-96/index.md
  site/ko/blog/new-in-devtools-96/index.md
  site/pt/blog/new-in-devtools-96/index.md
  site/ru/blog/new-in-devtools-96/index.md
  site/zh/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes

#1724 [lighthouse] What's new in Lighthouse 9.0
  site/en/blog/lighthouse-9-0/index.md
Labels: cla: yes, docs

#1734 [devtools-translate] Update translation
  site/zh/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes

#1731 YouTube embed for privacy segment from CDS keynote
  site/en/docs/privacy-sandbox/cds21-update/index.md
Labels: cla: yes, docs

#1727 translate new section
  site/ja/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes

#1729 New In Chrome 96 post
  site/en/blog/new-in-chrome-96/index.md
Labels: cla: yes

#1741 [devtools] Add video and fix typo
  site/en/blog/new-in-devtools-96/index.md
  site/es/blog/new-in-devtools-96/index.md
Labels: reviewers: devtools, cla: yes

#1717 [Privacy Sandbox] Glossary: WebID -> FedCM
  site/en/docs/privacy-sandbox/glossary/index.md
Labels: cla: yes

#1742 Adds token for the Auto Dark Origin Trial
  site/_includes/partials/meta.njk
  site/_scss/blocks/_project-icon.scss
Labels: cla: yes

#1752 [Privacy Sandbox] Fix UA Landing Page
  site/en/docs/privacy-sandbox/user-agent/index.md
Labels: cla: yes

#1749 FAQ for "How can I keep track of changes[…]?"
  site/en/docs/privacy-sandbox/faq/index.md
Labels: cla: yes, docs

#1736 Attribution reporting: two new blogposts
  site/en/docs/privacy-sandbox/attribution-reporting-event-guide/index.md
  site/en/docs/privacy-sandbox/attribution-reporting-event-introduction/index.md
  site/en/docs/privacy-sandbox/attribution-reporting-introduction/index.md
  site/en/docs/privacy-sandbox/attribution-reporting/index.md
Labels: cla: yes

#1756 Fixed big typo in title
  site/en/docs/privacy-sandbox/attribution-reporting-event-guide/index.md
Labels: cla: yes

#1754 Add deprecations/removals for Chrome 97.
  site/en/blog/deps-rems-97/index.md
Labels: cla: yes

#1737 [Privacy] Oct21 progress blog updates
  site/en/blog/progress-in-the-privacy-sandbox-2021-10/index.md
Labels: cla: yes

#1769 Pwa install article
  site/en/blog/pwa-install-features/index.md
Labels: cla: yes

#1772 Fix manifest description code sample
  site/en/docs/webstore/i18n/index.md
Labels: extensions, cla: yes

#1763 CUJ Tweaks for distributing extensions to enterprise users
  site/en/docs/webstore/cws-enterprise/index.md
Labels: extensions, cla: yes

#1766 CUJ Tweaks for "I want to stage my item to publish later"
  site/en/docs/webstore/publish/index.md
  site/en/docs/webstore/update/index.md
Labels: extensions, cla: yes

#1773 Document script.executeScript() promise behavior
  site/en/docs/extensions/reference/scripting/index.md
  site/en/docs/extensions/whatsnew/index.md
Labels: cla: yes

#1777 [devtools] What's New in DevTools (Chrome 97)
  site/_includes/partials/devtools/en/whats-new.md
  site/_includes/partials/devtools/es/whats-new.md
  site/_includes/partials/devtools/ja/whats-new.md
  site/_includes/partials/devtools/ko/whats-new.md
  site/_includes/partials/devtools/pt/whats-new.md
  site/_includes/partials/devtools/ru/whats-new.md
  site/_includes/partials/devtools/zh/whats-new.md
  site/en/blog/new-in-devtools-97/index.md
  site/es/blog/new-in-devtools-97/index.md
  site/ja/blog/new-in-devtools-97/index.md
  site/ko/blog/new-in-devtools-97/index.md
  site/pt/blog/new-in-devtools-97/index.md
  site/ru/blog/new-in-devtools-97/index.md
  site/zh/blog/new-in-devtools-97/index.md
Labels: reviewers: devtools, cla: yes

#1786 User-agent transformation code snippets
  site/en/docs/privacy-sandbox/user-agent/index.md
  site/en/docs/privacy-sandbox/user-agent/snippets/index.md
Labels: cla: yes

#1775 updating ajara's author info
  site/_data/authorsData.json
Labels: cla: yes

#1790 [devtools] Add docs for Chrome sync
  site/en/blog/new-in-devtools-97/index.md
Labels: reviewers: devtools, cla: yes

#1767 documentation: format `.json`
  site/en/docs/webstore/i18n/index.md
Labels: cla: yes

#1795 [devtools] Update sync documentation
  site/en/blog/new-in-devtools-97/index.md
  site/en/docs/devtools/customize/index.md
  site/es/blog/new-in-devtools-97/index.md
  site/ja/blog/new-in-devtools-97/index.md
  site/ko/blog/new-in-devtools-97/index.md
  site/pt/blog/new-in-devtools-97/index.md
  site/ru/blog/new-in-devtools-97/index.md
  site/zh/blog/new-in-devtools-97/index.md
Labels: reviewers: devtools, cla: yes

#1792 remove banner
  site/_data/banner.yml
Labels: cla: yes

#1788 Update description to match behavior.
  site/en/docs/extensions/mv3/manifest/web_accessible_resources/index.md
Labels: cla: yes

#1797 Progress in the Privacy Sandbox (November 2021)
  site/en/blog/progress-in-the-privacy-sandbox-2021-11/index.md
Labels: cla: yes
